service: cart-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: "eu-west-1"
  environment:
    PGUSER: "${env:PGUSER}"
    PGHOST: "${env:PGHOST}"
    PGPASSWORD: "${env:PGPASSWORD}"
    PGDATABASE: "${env:PGDATABASE}"
    PGPORT: "${env:PGPORT}"

useDotenv: true

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: "{proxy+}"
          cors: true
